# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\S.O.F.T.S\PIRENEA\PYTHON\sofa\src\gui\parameters_qt.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget_Parameters(object):
    def setupUi(self, DockWidget_Parameters):
        DockWidget_Parameters.setObjectName("DockWidget_Parameters")
        DockWidget_Parameters.resize(330, 315)
        DockWidget_Parameters.setMinimumSize(QtCore.QSize(330, 315))
        DockWidget_Parameters.setMaximumSize(QtCore.QSize(330, 315))
        DockWidget_Parameters.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        DockWidget_Parameters.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBox_Excit = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Excit.setGeometry(QtCore.QRect(10, 30, 311, 90))
        self.groupBox_Excit.setMinimumSize(QtCore.QSize(300, 70))
        self.groupBox_Excit.setMaximumSize(QtCore.QSize(320, 90))
        self.groupBox_Excit.setObjectName("groupBox_Excit")
        self.label_ExcitEnd = QtWidgets.QLabel(self.groupBox_Excit)
        self.label_ExcitEnd.setGeometry(QtCore.QRect(240, 45, 60, 16))
        self.label_ExcitEnd.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ExcitEnd.setObjectName("label_ExcitEnd")
        self.lineEdit_ExcitEnd = QtWidgets.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitEnd.setEnabled(False)
        self.lineEdit_ExcitEnd.setGeometry(QtCore.QRect(234, 65, 67, 20))
        self.lineEdit_ExcitEnd.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitEnd.setFont(font)
        self.lineEdit_ExcitEnd.setObjectName("lineEdit_ExcitEnd")
        self.lineEdit_ExcitStart = QtWidgets.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitStart.setEnabled(False)
        self.lineEdit_ExcitStart.setGeometry(QtCore.QRect(161, 65, 67, 20))
        self.lineEdit_ExcitStart.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitStart.setFont(font)
        self.lineEdit_ExcitStart.setObjectName("lineEdit_ExcitStart")
        self.label_ExcitStart = QtWidgets.QLabel(self.groupBox_Excit)
        self.label_ExcitStart.setGeometry(QtCore.QRect(163, 45, 65, 16))
        self.label_ExcitStart.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ExcitStart.setObjectName("label_ExcitStart")
        self.lineEdit_ExcitType = QtWidgets.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitType.setEnabled(False)
        self.lineEdit_ExcitType.setGeometry(QtCore.QRect(10, 20, 80, 20))
        self.lineEdit_ExcitType.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitType.setFont(font)
        self.lineEdit_ExcitType.setObjectName("lineEdit_ExcitType")
        self.lineEdit_ExcitIntensity = QtWidgets.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitIntensity.setEnabled(False)
        self.lineEdit_ExcitIntensity.setGeometry(QtCore.QRect(88, 65, 67, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitIntensity.setFont(font)
        self.lineEdit_ExcitIntensity.setObjectName("lineEdit_ExcitIntensity")
        self.lineEdit_ExcitDuration = QtWidgets.QLineEdit(self.groupBox_Excit)
        self.lineEdit_ExcitDuration.setEnabled(False)
        self.lineEdit_ExcitDuration.setGeometry(QtCore.QRect(12, 65, 70, 20))
        self.lineEdit_ExcitDuration.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_ExcitDuration.setFont(font)
        self.lineEdit_ExcitDuration.setObjectName("lineEdit_ExcitDuration")
        self.label_ExcitDuration = QtWidgets.QLabel(self.groupBox_Excit)
        self.label_ExcitDuration.setGeometry(QtCore.QRect(11, 45, 70, 16))
        self.label_ExcitDuration.setMinimumSize(QtCore.QSize(70, 0))
        self.label_ExcitDuration.setObjectName("label_ExcitDuration")
        self.label_ExcitIntensity = QtWidgets.QLabel(self.groupBox_Excit)
        self.label_ExcitIntensity.setGeometry(QtCore.QRect(87, 45, 70, 16))
        self.label_ExcitIntensity.setMinimumSize(QtCore.QSize(70, 0))
        self.label_ExcitIntensity.setObjectName("label_ExcitIntensity")
        self.groupBox_Eject = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Eject.setGeometry(QtCore.QRect(10, 130, 311, 98))
        self.groupBox_Eject.setMinimumSize(QtCore.QSize(300, 70))
        self.groupBox_Eject.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_Eject.setObjectName("groupBox_Eject")
        self.comboBox_EjectEnd = QtWidgets.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectEnd.setGeometry(QtCore.QRect(236, 69, 70, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectEnd.setFont(font)
        self.comboBox_EjectEnd.setObjectName("comboBox_EjectEnd")
        self.comboBox_EjectStart = QtWidgets.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectStart.setGeometry(QtCore.QRect(161, 69, 70, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectStart.setFont(font)
        self.comboBox_EjectStart.setObjectName("comboBox_EjectStart")
        self.label_EjectStart = QtWidgets.QLabel(self.groupBox_Eject)
        self.label_EjectStart.setGeometry(QtCore.QRect(164, 50, 65, 16))
        self.label_EjectStart.setObjectName("label_EjectStart")
        self.label_EjectEnd = QtWidgets.QLabel(self.groupBox_Eject)
        self.label_EjectEnd.setGeometry(QtCore.QRect(240, 50, 60, 16))
        self.label_EjectEnd.setObjectName("label_EjectEnd")
        self.comboBox_EjectIntensity = QtWidgets.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectIntensity.setGeometry(QtCore.QRect(86, 69, 70, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectIntensity.setFont(font)
        self.comboBox_EjectIntensity.setObjectName("comboBox_EjectIntensity")
        self.label_EjectIntensity = QtWidgets.QLabel(self.groupBox_Eject)
        self.label_EjectIntensity.setGeometry(QtCore.QRect(87, 50, 65, 16))
        self.label_EjectIntensity.setObjectName("label_EjectIntensity")
        self.label_EjectDuration = QtWidgets.QLabel(self.groupBox_Eject)
        self.label_EjectDuration.setGeometry(QtCore.QRect(11, 50, 65, 16))
        self.label_EjectDuration.setObjectName("label_EjectDuration")
        self.comboBox_EjectName = QtWidgets.QComboBox(self.groupBox_Eject)
        self.comboBox_EjectName.setGeometry(QtCore.QRect(10, 20, 81, 22))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_EjectName.setFont(font)
        self.comboBox_EjectName.setObjectName("comboBox_EjectName")
        self.lineEdit_EjectType = QtWidgets.QLineEdit(self.groupBox_Eject)
        self.lineEdit_EjectType.setEnabled(False)
        self.lineEdit_EjectType.setGeometry(QtCore.QRect(100, 20, 70, 20))
        self.lineEdit_EjectType.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_EjectType.setFont(font)
        self.lineEdit_EjectType.setObjectName("lineEdit_EjectType")
        self.lineEdit_EjectDuration = QtWidgets.QLineEdit(self.groupBox_Eject)
        self.lineEdit_EjectDuration.setEnabled(False)
        self.lineEdit_EjectDuration.setGeometry(QtCore.QRect(10, 69, 70, 20))
        self.lineEdit_EjectDuration.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_EjectDuration.setFont(font)
        self.lineEdit_EjectDuration.setObjectName("lineEdit_EjectDuration")
        self.lineEdit_File = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_File.setEnabled(False)
        self.lineEdit_File.setGeometry(QtCore.QRect(140, 10, 133, 20))
        self.lineEdit_File.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_File.setFont(font)
        self.lineEdit_File.setText("")
        self.lineEdit_File.setReadOnly(False)
        self.lineEdit_File.setObjectName("lineEdit_File")
        self.groupBox_Detect = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Detect.setGeometry(QtCore.QRect(10, 235, 311, 51))
        self.groupBox_Detect.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_Detect.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_Detect.setObjectName("groupBox_Detect")
        self.comboBox_DetectName = QtWidgets.QComboBox(self.groupBox_Detect)
        self.comboBox_DetectName.setGeometry(QtCore.QRect(10, 20, 81, 22))
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_DetectName.setFont(font)
        self.comboBox_DetectName.setObjectName("comboBox_DetectName")
        self.label_Filename = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_Filename.setGeometry(QtCore.QRect(70, 10, 60, 16))
        self.label_Filename.setObjectName("label_Filename")
        DockWidget_Parameters.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_Parameters)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_Parameters)

    def retranslateUi(self, DockWidget_Parameters):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_Parameters.setWindowTitle(_translate("DockWidget_Parameters", "Parameters"))
        self.groupBox_Excit.setTitle(_translate("DockWidget_Parameters", "Excitation"))
        self.label_ExcitEnd.setText(_translate("DockWidget_Parameters", "End (MHz)"))
        self.label_ExcitStart.setText(_translate("DockWidget_Parameters", "Start (MHz)"))
        self.label_ExcitDuration.setText(_translate("DockWidget_Parameters", "Dura. (ms)"))
        self.label_ExcitIntensity.setText(_translate("DockWidget_Parameters", "Intens. (%)"))
        self.groupBox_Eject.setTitle(_translate("DockWidget_Parameters", "Ejections"))
        self.label_EjectStart.setText(_translate("DockWidget_Parameters", "Start (MHz)"))
        self.label_EjectEnd.setText(_translate("DockWidget_Parameters", "End (MHz)"))
        self.label_EjectIntensity.setText(_translate("DockWidget_Parameters", "Intens. (%)"))
        self.label_EjectDuration.setText(_translate("DockWidget_Parameters", "Dura. (ms)"))
        self.groupBox_Detect.setTitle(_translate("DockWidget_Parameters", "Detection"))
        self.label_Filename.setText(_translate("DockWidget_Parameters", "FILENAME"))

